# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[manager]
show_hidden = true      # hidden files
ratio = [2, 3, 4]       # ratio of each block

[preview]
max_width = 3000
max_height = 3000
image_quality = 90

[opener]
edit = [
    { run = 'nvim "$@"', desc = "nvim", block = true }
]
